N = int(input("Você quer saber a tabuada do número?: "))
print(f"A tabuada do número {N} é:" )
print("-"*12)
print(f"{N} x {1:2} = {N*1}")
print(f"{N} x {2:2} = {N*2}")
print(f"{N} x {3:2} = {N*3}")
print(f"{N} x {4:2} = {N*4}")
print(f"{N} x {5:2} = {N*5}")
print(f"{N} x {6:2} = {N*6}")
print(f"{N} x {7:2} = {N*7}")
print(f"{N} x {8:2} = {N*8}")
print(f"{N} x {9:2} = {N*9}")
print(f"{N} x {10} = {N*10}")
print("-"*12)
